artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  feature_store_file_name: artifacts/data_ingestion/feature_store/flight_fare.csv
  training_file_name: artifacts/data_ingestion/dataset/train.csv
  testing_file_name: artifacts/data_ingestion/dataset/test.csv
  collection_name: Flight_price_prediction
  database_name: Flight_Price_Prediction