COLUMNS:
  Airline: object
  Date_of_Journey: object
  Source: object
  Destination: object
  Route: object
  Dep_Time: object
  Arrival_Time: object
  Duration: object
  Total_Stops: object
  Additional_Info: object

TARGET_COLUMN:
  name: Price

FEATURE_ENGINEERING_COLUMNS:
  airline: object
  source: object
  destination: object
  total_stops: int
  route_interaction: object
  month: int
  day: int
  duration_to_minutes: int
  dep_sin: float
  dep_cos: float
  arrival_sin: float
  arrival_cos: float
  duration_times_stops: int
  price: int